src/predicates/TilePredicates.ts
src/world/AbstractTile.ts

This replaces the previous dummy `tileName` string in `AbstractPredicate`. This way, the compiler doesn't let you use any subclass of `AbstractPredicate` that doesn't have a `static readonly tileName: string` as a target of a `TileWithinDistancePredicate`, letting the user know they need to fix that class's tile name implementation. Usage remains exactly the same, though.
It's annoying that we still can't require them to add the `tileName` property, but at least this way is safer and doesn't provide a default value if one hasn't been implemented.

Implement minor tileName cleanup

---

.gitignore
.travis.yml
package-lock.json
package.json
scripts/before_deploy/make_dist.sh
template.html
tsconfig.json
webpack.config.js

Adds configuration for Travis to build the project and deploy to GitHub Pages.
When deployment is triggered, the necessary resources are copied into a `deploy_dist` directory, and the contents of this are then pushed to an orphan `gh-pages` branch, which will be available at [here](https://GRarer.github.io/Aurora). The deployment process assumes that the necessary GitHub access token will be stored as a secure environment variable in the repo's Travis configurations under the name `GITHUB_TOKEN`.
This also adds webpack and related plugins in order to optimize and minify the HTML/CSS/JS into a single HTML file during deployment. This is only important for deployment, not local development; we don't care what deployed code looks like, only that it runs correctly and fast. The minification …

Add Travis CI integration and GitHub Pages deployment

---

src/App.ts
src/UI/Images.ts

Make sure that we explicitly wait for all images to be prefetched before rendering the main menu. In some cases, `Image` preloading magic will do this for us, but it's not an invariant.

Explicitly block on preloading images

---

src/util/Cheats.ts

Freeze the `Resource` and `Species` constructors so that the player cannot add or modify the multitons when cheats are enabled.
It is not possible to prevent them from accessing the constructor, though, so `new Resources('foo')` would be possible but probably unhelpful.

Remove ability to modify resources/species with cheats enabled

---

src/UI/transitionScreen/Quote.ts
src/UI/transitionScreen/TransitionScreen.ts
src/util/Text.ts

Adds a `stripIndent` tagged template for sensibly creating multiline indented
quotes without caring about indentation:
```
new Quote(stripIndent`
Multiline versions are also possible,
and they can use indentation.
Line breaks are also supported.`,
"Author Goes Here"
),
```
The level of the minimal amount of indentation across all lines (not counting
empty lines as 0 indentation) is removed from each line. For example, the line
"and they can use indentation" above would end up with no indentation. It also
strips any leading and trailing newlines; the resulting string above would not
have a leading newline.
Also change the leading quotation mark in Quote rendering to be inserted after
any leading indentation.
Also removes an extraneous `console.log`.

Add stripIndent tagged template for multiline indented quotes

---

bundle.config.js
ci/scripts/before_deploy/make_dist.sh
index.html
package-lock.json
package.json
readme.md
src/UI/UI.ts
src/types/twemoji-parser.d.ts
stylesheets/styles.css
tsconfig.json

Add the [twemoji](https://github.com/twitter/twemoji) library in order to patch emoji into SVGs with a consistent appearance. Introduces basic function in `UI` for interacting with the library, and makes all text elements patch emoji by default if their text contains it.
Since we test the project by locally hosting it, introducing external libraries makes it impossible with our current setup to resolve dependencies in `node_modules`. Therefore, this also modifies the build process to run minimal webpack bundling over the build output; we don't attempt to minify or inline anything, since that would be slow. Since this necessarily dumps output to one output file, source maps are also created during the build process, which webpack inherits. Now, despite the obfuscated build output, the …

Add twemoji and automatically patch emoji for text elements

---

.eslintrc.js
package-lock.json
package.json

Sets up ESLint and typescript-eslint rules in order to give feedback on style and coding practices. Also adds a new node script `npm run lint` to run the linter. The following rules have been enabled:
* Disallow unused variables/imports
* `@typescript-eslint/no-unused-vars` (error)
* Disallow using variables/functions/classes/enums/types before they're defined
* `@typescript-eslint/no-use-before-define` (error)
* Enforce annotating function types and return types
* `@typescript-eslint/explicit-function-return-type` (error)
* Enforce that in `foo + bar`, the variables are either both numbers or both strings
* `@typescript-eslint/restrict-plus-operands` (error)
* Prefer `x` and `!x` over `x === true` and `x === false`
* `@typescript-eslint/no-unnecessary-boolean-literal-compare` (error)
* …

Set up eslint and add linting rules

---

.travis.yml
ci/package-lock.json
ci/package.json

Currently, `node_modules` is around 282M in size. This includes all of the webpack-related dependencies for aggressively minifying the build output into a single `index.html`, even though only the CI needs to do this, not developers. This splits off these dependencies into `ci/package.json` and `ci/package-lock.json`, which the CI will use instead of the top-level ones when minifying before deploying. This more than halves the size of `node_modules` to around 128M.
Additionally, this also changes the Travis config to use `npm ci` instead of `npm install` when installing dependencies, as it is more deterministic.

Move CI minification dependencies to separate package.json

---

.eslintrc.js
src/Game.ts
src/UI/GameWindow.ts
src/UI/menu/CreditsScreen.ts
src/UI/menu/MainMenu.ts
src/UI/productionScreen/ProductionScreen.ts
src/UI/researchScreen/ResearchScreen.ts
src/UI/transitionScreen/TransitionScreen.ts
src/UI/worldScreen/MapUI.ts
src/UI/worldScreen/WorldScreen.ts
src/world/Tiles/Habitat.ts

Adds the following linting rules:
- `spaced-comment`: prefer `// foo` over `//foo`
- `array-bracket-spacing`: prefer `[foo]` over `[ foo ]`
- `object-curly-spacing`: prefer `{ foo }` over `{foo}`
Also fixes the corresponding violations that were caught.
These are probably the last of the stylistic linting rules that should be added.

Add more stylistic linting rules and fix associated errors

---

ci/package-lock.json
ci/package.json
package-lock.json
package.json
src/Game.ts
src/UI/productionScreen/ProductionScreen.ts
src/util/Arrays.ts
stylesheets/productionscreen.css

Changes the costly conversion priority list on the production screen to be a drag-and-drop menu. Moves the toggling to an adjacent button, rather than clicking the conversion itself.
Also modifies the structure of conversion priorities. Instead of moving priority levels up and down the list of all costly conversions, the primary API for swapping priorities is to shift a costly conversion to a different index.
Finally, this also cleans up the `this.run.getResourceConversions()` to separate the free from the costly conversions. The old behavior, which returned a list containing all free conversions followed by all costly conversions in order of decreasing priority, has been moved to `getAllResourceConversions()`.

Implement drag-and-drop menu on the production screen

---

.eslintrc.js
src/UI/Images.ts
src/UI/menu/CreditsScreen.ts
src/UI/productionScreen/ProductionScreen.ts
src/UI/transitionScreen/TransitionScreen.ts
src/UI/worldScreen/TileSidebar.ts
src/predicates/WorldPredicates.ts
src/quests/QuestStage.ts
src/resources/Cost.ts
src/resources/Inventory.ts
src/resources/Resource.ts
src/resources/Species.ts
src/techtree/Technology.ts
src/tileProjects/TileProject.ts
src/util/Cheats.ts
src/util/Quantities.ts
src/util/Text.ts

Adds the following rules:
- `no-unneeded-ternary`: prefer things like `x || y` over `x ? x : y`
- `prefer-const`: prefer `const` over `let` when possible
- `no-fallthrough`: don't allow fallthrough in switch statements
- `use-isnan`: don't allow comparisons to `NaN`
- `block-spacing`: prefer `{ ... }` over `{...}` for functions
- `semi-spacing`: don't allow spaces before semicolons
- `space-before-blocks`: prefer `(...) {` over `(...){`
- `prefer-object-spread`: prefer object spreads over `Object.assign`
Also fixes the corresponding existing violations.

Add more ESLint style rules

---

src/Game.ts

When dragging a constly conversion from one spot to another, the
priorities should be shifted in the opposite direction as the items in
the list; the dragged element should receive the priority of the target
index, not the other way around.
Resolves GRarer/Aurora#40.

Fix incorrect priority conversion menu shifting

---

.eslintrc.js
src/UI/worldScreen/MapUI.ts
src/UI/worldScreen/WorldScreenHeader.ts
src/world/Tiles/Lander.ts

Add the following rules:
* `space-infix-ops`: Prefer `a + b` over `a+b`, etc.
* `comma-style`: Reinforce comma style for multiline comma-separated blocks
* `no-trailing-spaces`: Disallow trailing whitespace
Also fixes the `space-infix-ops`-related violations.

Even more linting and fixes

---

src/UI/transitionScreen/Quote.ts
src/util/Arrays.ts
src/util/Random.ts
src/world/Tiles/Wasteland.ts
src/world/World.ts

Uses a new `Random.fromWeightedArray` to do Wasteland random texture selection instead of manually replicating elements to give them a bias.

Refactor Wasteland random texture selection

---

ci/package-lock.json
ci/package.json
ci/webpack.config.js

Use `url-loader` to inline fonts under 100000, or fall back to `file-loader` otherwise.

Inline fonts using url-loader in webpack

---

src/resources/Resource.ts
src/resources/Species.ts
src/util/Objects.ts

The querying of the list of all `Resource` instances by looking at the keys of `Resource` was not safe, and was liable to break in the context of code transformations. This may be the cause of the bug on GitHub pages in which an extra resource, shown as the empty string, was displayed when using cheats; this likely corresponds to the extra key `values: () => Resource[]` in `typeof Resource`. This improves the typing of that function, and ensures that only instances of `Resource` are returned in the list, rather than unsafely casting.

Fix bug with getting list of resource by key

---

src/util/Newtypes.ts

Adds a way to construct **newtypes**, which are like a type aliases, but they create a distinct type. A newtype also has the same runtime representation as its underlying type; there is no boxing overhead.
Adding newtypes can be a useful tool in refactoring.
To initialize a newtype `USD` that has the same representation as `number`:
```typescript
// The type itself
type USD = Newtype<{ readonly USD: unique symbol; }, number>;
// The newtype converter
const USD = newtype<USD>();
```
Unfortunately, the `{ readonly USD: unique symbol; }` is necessary boilerplate that I haven't figured out how to avoid.
Then, you can convert back and forth:
```typescript
// Convert type into newtype wrapper
const usd: USD = USD.wrap(3);
// Convert newtype into underlying type
const three: number = …
```

Add newtype functionality

---

src/music/Drums.ts
src/music/Instruments.ts
src/music/MusicManager.ts
src/music/Notes.ts
src/music/Rhythm.ts
src/music/Samples.ts
src/music/Scales.ts
src/util/Newtypes.ts

Adds the following newtype wrappers over `number` in the music code:
- `MidiNumber`: corresponds to an absolute note
- Example: middle C (C4) has a `MidiNumber` of 60
- `Frequency`: the frequency (in Hertz) used by WebAudio to play a note
- Example: A4 has a `Frequency` of 440
- `Pitch`: offset into 12-tone chromatic scale relative to C
- Example: an E would have a `Pitch` of 4
- Can also be outside of this range, but can be normalized with mod
- Does not represent an absolute note by itself; must be converted to a `MidiNumber` by assigning it to be relative to some octave
- Note that a `Pitch` plus a `PitchOffset` is a new `Pitch`, though not necessarily normalized to 0-11
- `PitchOffset`: offset, in semitones, from a pitch
- Example: an E relative to a D would have a `PitchOffset` of 2 …

Add newtypes to music code

---

src/App.ts
src/music/Drums.ts
src/music/Instrument.ts
src/music/Instruments.ts
src/music/MusicManager.ts
src/music/Samples.ts

Fix the discarded promise from #70. To fix this, most relevant queuing functions are marked `async` all the way up to `MusicManager.initialize`. Some new functions are added to assist with lifting promise awaiting through the construction of an object.
I'd like @MayMoonsley to listen to this to make sure it sounds correct, and to help debug if it doesn't. I did a lot of things here that could potentially mess with the timing, and she's a lot more familiar with that than me.
Also removes `SampleNames`, which adds safety that the compiler can figure out on its own.
Resolves #70

Make music code async, fix discarded promise

---

src/UI/transitionScreen/Quote.ts
src/util/Text.ts

Modifies `stripIndent` to allow single newlines to behave as line continuations, replacing them with a space. When two or more newlines are used, it removes the first one as an indicator that newlines should be inserted instead of a line continuation. As before, the least-indented nonempty line is used as the baseline for indentation, and leading and trailing newlines are stripped, letting you write text blocks like the following:
```typescript
const str = stripIndent`
A long text block with line continuations; this
break will be treated as a space, and there will
be one newline between "will" and "be".
`;
```
Uses this functionality to wrap the quotes in `Quotes`.

Use text block line continuations to wrap long strings

---

src/util/Text.ts

Fix bug where `reduce` failed when there were lines, but no considered indentation levels. This would cause it to fail on inputs such as the empty string.

Fix stripIndent bug on empty string

---

src/music/MusicManager.ts
src/music/Samples.ts
src/polyfills/AudioBuffer.prototype.copyToChannel.ts

I found that even recent implementations of WebAudio in WebKit-based browsers could lack the following features that the music code needs:
- `window.AudioContext`
- Fall back to `window.webkitAudioContext` if it's not available; throw if neither are available
- `AudioContext.prototype.decodeAudioData`'s callback parameters were not optional
- Instead, wrap this in a `new Promise`, and pass `resolve`/`reject` as the callbacks
- The compiler doesn't recognize that this returns `void` when callbacks are provided, so we have to cast the result
- `AudioNode`'s constructor
- Instead, use `AudioContext.prototype.createBuffer`
- `AudioNode.prototype.copyToChannel`
- Instead, use `AudioNode.prototype.getChannelData` and copy the data into the resulting `Float32Array` manually
For convenience, …

Refactor music code for WebKit WebAudio compatiblity

---

src/App.ts
src/UI/UI.ts
src/UI/menu/MainMenu.ts
src/UI/menu/SettingsScreen.ts
src/music/MusicManager.ts
src/persistence/Settings.ts

This does two things:
- connects the music volume to the volume controls in the settings page
- adds a start/stop music button to the main menu
A slight challenge with the latter was that the music did not have the ability to stop. The most obvious solution is just to have a `isPlaying: boolean` that tracks whether or not music is playing, and have the measure generation cancel itself if it's not supposed to be playing. Unfortunately, this could run into a race condition that would fail to cancel the music, causing multiple music instances to run at the same time. The best way to implement this kind of thing would be to have the ability to cancel promises. Unfortunately, JS doesn't have async exceptions, masking, etc. Instead, we have to resort to a more naive implementation that does the …

Music menu integration

---

src/UI/UI.ts
src/UI/menu/MainMenu.ts
src/UI/menu/PauseMenu.ts
src/UI/menu/SettingsScreen.ts
src/UI/worldScreen/WorldScreenHeader.ts

Replaces the `Quit Game` button on the world screen with a pause menu that lets you change settings, enable/disable audio, quit the game, or resume. Previously, we could not change settings or enable/disable audio without quitting the game to the main menu.
Creation of the button to enable/disable music has been extracted to a static method in `MainMenu` so it can be reused in the pause menu. If there's a better place to put this, let me know.

Add pause screen for changing settings/audio in game

---

ci/webpack.config.js
stylesheets/menus.css

Use a non-relative path for `planet.png`. This introduces a webpack error since it can't resolve `.png` files, so use `file-loader` to resolve the PNGs, substituting any path in `assets` to correct the URL. Furthermore, prevent redundant output of resolved assets to `dist` during minification.
This should fix the issue of `planet.png` 404'ing on GitHub pages; if we only correct the URL to the relative path `assets/ui/planet.png`, it will work correctly on GitHub pages but not on live-server.

Fix URL handling of PNG files in webpack

---

src/util/Random.ts

Fixes consistent crash after 29 (I think) turns.
Since `shuffle` didn't actually allocate a new array, the quotes list was being emptied as the individual quotes were popped from the sample. When the sample was supposed to be refilled from the quotes list, both arrays eventually ended up empty, and they would loop forever as it counted `undefined` as a repeated quote.

Fix crash after quotes list is exhausted
